import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Caveat } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], display: "swap" ,variable: "--font-inter" });
const caveat = Caveat({ subsets: ["latin"], display: "swap", variable:"--font-caveat"})

export const metadata: Metadata = {
  title: "Hari Pajjuri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={`${inter.variable} ${caveat.variable}`}>{children}</body>
    </html>
  );
}
